
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: go-simple-server
  labels:
    app: go-simple-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-simple-server
  template:
    metadata:
      labels:
        app: go-simple-server
    spec:
      containers:
      - name: go-simple-server
        image: us-central1-docker.pkg.dev/marifw-gke-main/marifw-container-repo/go-simple-server
        ports:
        - containerPort: 8080